// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string[]} paths
 * @param {boolean} removeCatalogRows
 * @returns {$CancellablePromise<$models.ArchiveResponse>}
 */
export function Archive(paths, removeCatalogRows) {
    return $Call.ByID(4115508224, paths, removeCatalogRows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function CancelScan() {
    return $Call.ByID(4269477905);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(867481190);
}

/**
 * @param {string} format
 * @param {string} contents
 * @param {string} suggestedName
 * @returns {$CancellablePromise<string>}
 */
export function ExportSnapshot(format, contents, suggestedName) {
    return $Call.ByID(846080476, format, contents, suggestedName);
}

/**
 * @returns {$CancellablePromise<$models.CatalogView>}
 */
export function GetCatalog() {
    return $Call.ByID(1779499453).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Diagnostics>}
 */
export function GetDiagnostics() {
    return $Call.ByID(3665810494).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ScanStatus>}
 */
export function GetScanStatus() {
    return $Call.ByID(219575685).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.StorageSettings>}
 */
export function GetSettings() {
    return $Call.ByID(1126039811).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} kind
 * @param {string} initial
 * @returns {$CancellablePromise<string>}
 */
export function PickStoragePath(kind, initial) {
    return $Call.ByID(1120797135, kind, initial);
}

/**
 * @param {string} filename
 * @param {number} limit
 * @returns {$CancellablePromise<$models.ContextPreview>}
 */
export function Preview(filename, limit) {
    return $Call.ByID(1321728342, filename, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string[]} paths
 * @param {boolean} removeCatalogRows
 * @returns {$CancellablePromise<$models.RecycleResponse>}
 */
export function Recycle(paths, removeCatalogRows) {
    return $Call.ByID(954983175, paths, removeCatalogRows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} confirm
 * @param {string[]} threadIDs
 * @returns {$CancellablePromise<$models.CatalogMutation>}
 */
export function RemoveCatalogRows(confirm, threadIDs) {
    return $Call.ByID(1457330696, confirm, threadIDs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function Reveal(filename) {
    return $Call.ByID(3554946431, filename);
}

/**
 * @param {string[]} paths
 * @param {boolean} removeCatalogRows
 * @returns {$CancellablePromise<$models.ArchiveReview>}
 */
export function ReviewArchive(paths, removeCatalogRows) {
    return $Call.ByID(2681842648, paths, removeCatalogRows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string[]} paths
 * @param {boolean} removeCatalogRows
 * @returns {$CancellablePromise<$models.RecycleReview>}
 */
export function ReviewRecycle(paths, removeCatalogRows) {
    return $Call.ByID(2051100959, paths, removeCatalogRows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {$models.StorageSettingsUpdate} update
 * @returns {$CancellablePromise<$models.StorageSettings>}
 */
export function SaveSettings(update) {
    return $Call.ByID(3488655450, update).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} rootID
 * @param {string} title
 * @returns {$CancellablePromise<$models.TitleAlias>}
 */
export function SaveTitleAlias(rootID, title) {
    return $Call.ByID(2742560137, rootID, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {boolean} includeArchived
 * @returns {$CancellablePromise<$models.ScanResult>}
 */
export function Scan(includeArchived) {
    return $Call.ByID(2634642607, includeArchived).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {string} filename
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<$models.ContextSearch>}
 */
export function SearchContext(filename, query, limit) {
    return $Call.ByID(1312672381, filename, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ArchiveResponse.createFrom;
const $$createType1 = $models.CatalogView.createFrom;
const $$createType2 = $models.Diagnostics.createFrom;
const $$createType3 = $models.ScanStatus.createFrom;
const $$createType4 = $models.StorageSettings.createFrom;
const $$createType5 = $models.ContextPreview.createFrom;
const $$createType6 = $models.RecycleResponse.createFrom;
const $$createType7 = $models.CatalogMutation.createFrom;
const $$createType8 = $models.ArchiveReview.createFrom;
const $$createType9 = $models.RecycleReview.createFrom;
const $$createType10 = $models.TitleAlias.createFrom;
const $$createType11 = $models.ScanResult.createFrom;
const $$createType12 = $models.ContextSearch.createFrom;
