// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CatalogCheck {
    /**
     * Creates a new CatalogCheck instance.
     * @param {Partial<CatalogCheck>} [$$source = {}] - The source object to create the CatalogCheck.
     */
    constructor($$source = {}) {
        if (!("dbPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dbPath"] = "";
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("threadIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["threadIds"] = [];
        }
        if (!("requested" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requested"] = 0;
        }
        if (!("backupRequired" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["backupRequired"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogCheck instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CatalogCheck}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("threadIds" in $$parsedSource) {
            $$parsedSource["threadIds"] = $$createField2_0($$parsedSource["threadIds"]);
        }
        return new CatalogCheck(/** @type {Partial<CatalogCheck>} */($$parsedSource));
    }
}

export class CatalogMutation {
    /**
     * Creates a new CatalogMutation instance.
     * @param {Partial<CatalogMutation>} [$$source = {}] - The source object to create the CatalogMutation.
     */
    constructor($$source = {}) {
        if (!("removed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["removed"] = 0;
        }
        if (!("ids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ids"] = [];
        }
        if (!("backupPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backupPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogMutation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CatalogMutation}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ids" in $$parsedSource) {
            $$parsedSource["ids"] = $$createField1_0($$parsedSource["ids"]);
        }
        return new CatalogMutation(/** @type {Partial<CatalogMutation>} */($$parsedSource));
    }
}

export class CatalogRow {
    /**
     * Creates a new CatalogRow instance.
     * @param {Partial<CatalogRow>} [$$source = {}] - The source object to create the CatalogRow.
     */
    constructor($$source = {}) {
        if (!("host_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_id"] = "";
        }
        if (!("thread_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["thread_id"] = "";
        }
        if (!("display_title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_title"] = "";
        }
        if (!("source_created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_created_at"] = "";
        }
        if (!("source_updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_updated_at"] = "";
        }
        if (!("cwd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cwd"] = "";
        }
        if (!("source_kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_kind"] = "";
        }
        if (!("source_detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_detail"] = "";
        }
        if (!("model_provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model_provider"] = "";
        }
        if (!("git_branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["git_branch"] = "";
        }
        if (!("observation_sequence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["observation_sequence"] = 0;
        }
        if (!("missing_candidate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["missing_candidate"] = 0;
        }
        if (!("thread_source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["thread_source"] = "";
        }
        if (!("source_recency_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_recency_at"] = "";
        }
        if (!("pending_observed_title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pending_observed_title"] = "";
        }
        if (!("orphaned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["orphaned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CatalogRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CatalogRow(/** @type {Partial<CatalogRow>} */($$parsedSource));
    }
}

export class CatalogView {
    /**
     * Creates a new CatalogView instance.
     * @param {Partial<CatalogView>} [$$source = {}] - The source object to create the CatalogView.
     */
    constructor($$source = {}) {
        if (!("dbPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dbPath"] = "";
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {CatalogRow[]}
             */
            this["rows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CatalogView}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField3_0($$parsedSource["rows"]);
        }
        return new CatalogView(/** @type {Partial<CatalogView>} */($$parsedSource));
    }
}

export class ContextMessage {
    /**
     * Creates a new ContextMessage instance.
     * @param {Partial<ContextMessage>} [$$source = {}] - The source object to create the ContextMessage.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContextMessage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContextMessage(/** @type {Partial<ContextMessage>} */($$parsedSource));
    }
}

export class ContextPreview {
    /**
     * Creates a new ContextPreview instance.
     * @param {Partial<ContextPreview>} [$$source = {}] - The source object to create the ContextPreview.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("messages" in $$source)) {
            /**
             * @member
             * @type {ContextMessage[]}
             */
            this["messages"] = [];
        }
        if (!("limited" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["limited"] = false;
        }
        if (!("readError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["readError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContextPreview}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField2_0($$parsedSource["messages"]);
        }
        return new ContextPreview(/** @type {Partial<ContextPreview>} */($$parsedSource));
    }
}

export class ContextSearch {
    /**
     * Creates a new ContextSearch instance.
     * @param {Partial<ContextSearch>} [$$source = {}] - The source object to create the ContextSearch.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("query" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["query"] = "";
        }
        if (!("matches" in $$source)) {
            /**
             * @member
             * @type {ContextMessage[]}
             */
            this["matches"] = [];
        }
        if (!("scannedBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scannedBytes"] = 0;
        }
        if (!("complete" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["complete"] = false;
        }
        if (!("readError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["readError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextSearch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContextSearch}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField2_0($$parsedSource["matches"]);
        }
        return new ContextSearch(/** @type {Partial<ContextSearch>} */($$parsedSource));
    }
}

export class Group {
    /**
     * Creates a new Group instance.
     * @param {Partial<Group>} [$$source = {}] - The source object to create the Group.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("rootId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rootId"] = "";
        }
        if (!("storage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storage"] = "";
        }
        if (!("archived" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["archived"] = false;
        }
        if (!("sourceLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceLabel"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("titleSource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["titleSource"] = "";
        }
        if (!("prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prompt"] = "";
        }
        if (!("cwd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cwd"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("fileCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileCount"] = 0;
        }
        if (!("lastActivity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastActivity"] = "";
        }
        if (!("agents" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["agents"] = [];
        }
        if (!("rootPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rootPath"] = "";
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {SessionFile[]}
             */
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Group}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType0;
        const $$createField14_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("agents" in $$parsedSource) {
            $$parsedSource["agents"] = $$createField12_0($$parsedSource["agents"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField14_0($$parsedSource["files"]);
        }
        return new Group(/** @type {Partial<Group>} */($$parsedSource));
    }
}

export class RecycleCheck {
    /**
     * Creates a new RecycleCheck instance.
     * @param {Partial<RecycleCheck>} [$$source = {}] - The source object to create the RecycleCheck.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("threadId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["threadId"] = "";
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("currentSizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentSizeBytes"] = 0;
        }
        if (!("scannedSizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scannedSizeBytes"] = 0;
        }
        if (!("currentLastModified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentLastModified"] = "";
        }
        if (!("scannedLastModified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scannedLastModified"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecycleCheck instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecycleCheck}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecycleCheck(/** @type {Partial<RecycleCheck>} */($$parsedSource));
    }
}

export class RecycleItem {
    /**
     * Creates a new RecycleItem instance.
     * @param {Partial<RecycleItem>} [$$source = {}] - The source object to create the RecycleItem.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecycleItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecycleItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecycleItem(/** @type {Partial<RecycleItem>} */($$parsedSource));
    }
}

export class RecycleResponse {
    /**
     * Creates a new RecycleResponse instance.
     * @param {Partial<RecycleResponse>} [$$source = {}] - The source object to create the RecycleResponse.
     */
    constructor($$source = {}) {
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {RecycleItem[]}
             */
            this["result"] = [];
        }
        if (!("catalog" in $$source)) {
            /**
             * @member
             * @type {{"requested": number, "removed": number, "ids": string[], "backupPath": string, "error": string}}
             */
            this["catalog"] = {"requested": 0, "removed": 0, "ids": [], "backupPath": "", "error": ""};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecycleResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecycleResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField0_0($$parsedSource["result"]);
        }
        if ("catalog" in $$parsedSource) {
            $$parsedSource["catalog"] = $$createField1_0($$parsedSource["catalog"]);
        }
        return new RecycleResponse(/** @type {Partial<RecycleResponse>} */($$parsedSource));
    }
}

export class RecycleReview {
    /**
     * Creates a new RecycleReview instance.
     * @param {Partial<RecycleReview>} [$$source = {}] - The source object to create the RecycleReview.
     */
    constructor($$source = {}) {
        if (!("safe" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["safe"] = false;
        }
        if (!("totalBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalBytes"] = 0;
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {RecycleCheck[]}
             */
            this["files"] = [];
        }
        if (!("catalog" in $$source)) {
            /**
             * @member
             * @type {CatalogCheck}
             */
            this["catalog"] = (new CatalogCheck());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecycleReview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecycleReview}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType11;
        const $$createField3_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField2_0($$parsedSource["files"]);
        }
        if ("catalog" in $$parsedSource) {
            $$parsedSource["catalog"] = $$createField3_0($$parsedSource["catalog"]);
        }
        return new RecycleReview(/** @type {Partial<RecycleReview>} */($$parsedSource));
    }
}

export class ScanResult {
    /**
     * Creates a new ScanResult instance.
     * @param {Partial<ScanResult>} [$$source = {}] - The source object to create the ScanResult.
     */
    constructor($$source = {}) {
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (!("archivedRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archivedRoot"] = "";
        }
        if (!("scannedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scannedAt"] = "";
        }
        if (!("indexHits" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["indexHits"] = 0;
        }
        if (!("indexMisses" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["indexMisses"] = 0;
        }
        if (!("stats" in $$source)) {
            /**
             * @member
             * @type {Stats}
             */
            this["stats"] = (new Stats());
        }
        if (!("currentStats" in $$source)) {
            /**
             * @member
             * @type {Stats}
             */
            this["currentStats"] = (new Stats());
        }
        if (!("archivedStats" in $$source)) {
            /**
             * @member
             * @type {Stats}
             */
            this["archivedStats"] = (new Stats());
        }
        if (!("roots" in $$source)) {
            /**
             * @member
             * @type {ScanRoot[]}
             */
            this["roots"] = [];
        }
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {Group[]}
             */
            this["groups"] = [];
        }
        if (!("archivedGroups" in $$source)) {
            /**
             * @member
             * @type {Group[]}
             */
            this["archivedGroups"] = [];
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {SessionFile[]}
             */
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType13;
        const $$createField6_0 = $$createType13;
        const $$createField7_0 = $$createType13;
        const $$createField8_0 = $$createType15;
        const $$createField9_0 = $$createType17;
        const $$createField10_0 = $$createType17;
        const $$createField11_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField5_0($$parsedSource["stats"]);
        }
        if ("currentStats" in $$parsedSource) {
            $$parsedSource["currentStats"] = $$createField6_0($$parsedSource["currentStats"]);
        }
        if ("archivedStats" in $$parsedSource) {
            $$parsedSource["archivedStats"] = $$createField7_0($$parsedSource["archivedStats"]);
        }
        if ("roots" in $$parsedSource) {
            $$parsedSource["roots"] = $$createField8_0($$parsedSource["roots"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField9_0($$parsedSource["groups"]);
        }
        if ("archivedGroups" in $$parsedSource) {
            $$parsedSource["archivedGroups"] = $$createField10_0($$parsedSource["archivedGroups"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField11_0($$parsedSource["files"]);
        }
        return new ScanResult(/** @type {Partial<ScanResult>} */($$parsedSource));
    }
}

export class ScanRoot {
    /**
     * Creates a new ScanRoot instance.
     * @param {Partial<ScanRoot>} [$$source = {}] - The source object to create the ScanRoot.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("archived" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["archived"] = false;
        }
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("stats" in $$source)) {
            /**
             * @member
             * @type {Stats}
             */
            this["stats"] = (new Stats());
        }
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {Group[]}
             */
            this["groups"] = [];
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {SessionFile[]}
             */
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanRoot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanRoot}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType13;
        const $$createField6_0 = $$createType17;
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField5_0($$parsedSource["stats"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField6_0($$parsedSource["groups"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField7_0($$parsedSource["files"]);
        }
        return new ScanRoot(/** @type {Partial<ScanRoot>} */($$parsedSource));
    }
}

export class ScanStatus {
    /**
     * Creates a new ScanStatus instance.
     * @param {Partial<ScanStatus>} [$$source = {}] - The source object to create the ScanStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("cancelable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cancelable"] = false;
        }
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }
        if (!("filesTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesTotal"] = 0;
        }
        if (!("filesCompleted" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesCompleted"] = 0;
        }
        if (!("indexHits" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["indexHits"] = 0;
        }
        if (!("indexMisses" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["indexMisses"] = 0;
        }
        if (!("cancelled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cancelled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanStatus(/** @type {Partial<ScanStatus>} */($$parsedSource));
    }
}

export class SessionFile {
    /**
     * Creates a new SessionFile instance.
     * @param {Partial<SessionFile>} [$$source = {}] - The source object to create the SessionFile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("parent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parent"] = "";
        }
        if (!("rootId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rootId"] = "";
        }
        if (!("cwd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cwd"] = "";
        }
        if (!("agent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent"] = "";
        }
        if (!("prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prompt"] = "";
        }
        if (!("sessionTimestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionTimestamp"] = "";
        }
        if (!("lastModified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastModified"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("sizeGiB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeGiB"] = 0;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("readError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["readError"] = "";
        }
        if (!("storage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storage"] = "";
        }
        if (!("archived" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["archived"] = false;
        }
        if (!("groupTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["groupTitle"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionFile(/** @type {Partial<SessionFile>} */($$parsedSource));
    }
}

export class Stats {
    /**
     * Creates a new Stats instance.
     * @param {Partial<Stats>} [$$source = {}] - The source object to create the Stats.
     */
    constructor($$source = {}) {
        if (!("fileCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileCount"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalBytes"] = 0;
        }
        if (!("totalGiB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalGiB"] = 0;
        }
        if (!("groupCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["groupCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stats(/** @type {Partial<Stats>} */($$parsedSource));
    }
}

export class StorageLocations {
    /**
     * Creates a new StorageLocations instance.
     * @param {Partial<StorageLocations>} [$$source = {}] - The source object to create the StorageLocations.
     */
    constructor($$source = {}) {
        if (!("currentRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentRoot"] = "";
        }
        if (!("archivedRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archivedRoot"] = "";
        }
        if (!("catalogDb" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["catalogDb"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageLocations instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StorageLocations}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StorageLocations(/** @type {Partial<StorageLocations>} */($$parsedSource));
    }
}

export class StorageSettings {
    /**
     * Creates a new StorageSettings instance.
     * @param {Partial<StorageSettings>} [$$source = {}] - The source object to create the StorageSettings.
     */
    constructor($$source = {}) {
        if (!("currentRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentRoot"] = "";
        }
        if (!("archivedRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archivedRoot"] = "";
        }
        if (!("catalogDb" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["catalogDb"] = "";
        }
        if (!("settingsPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["settingsPath"] = "";
        }
        if (!("defaults" in $$source)) {
            /**
             * @member
             * @type {StorageLocations}
             */
            this["defaults"] = (new StorageLocations());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StorageSettings}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("defaults" in $$parsedSource) {
            $$parsedSource["defaults"] = $$createField4_0($$parsedSource["defaults"]);
        }
        return new StorageSettings(/** @type {Partial<StorageSettings>} */($$parsedSource));
    }
}

export class StorageSettingsUpdate {
    /**
     * Creates a new StorageSettingsUpdate instance.
     * @param {Partial<StorageSettingsUpdate>} [$$source = {}] - The source object to create the StorageSettingsUpdate.
     */
    constructor($$source = {}) {
        if (!("currentRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentRoot"] = "";
        }
        if (!("archivedRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archivedRoot"] = "";
        }
        if (!("catalogDb" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["catalogDb"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageSettingsUpdate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StorageSettingsUpdate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StorageSettingsUpdate(/** @type {Partial<StorageSettingsUpdate>} */($$parsedSource));
    }
}

export class TitleAlias {
    /**
     * Creates a new TitleAlias instance.
     * @param {Partial<TitleAlias>} [$$source = {}] - The source object to create the TitleAlias.
     */
    constructor($$source = {}) {
        if (!("rootId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rootId"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TitleAlias instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TitleAlias}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TitleAlias(/** @type {Partial<TitleAlias>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CatalogRow.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ContextMessage.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = SessionFile.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = RecycleItem.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Struct({
    "ids": $$createType0,
});
const $$createType10 = RecycleCheck.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = CatalogCheck.createFrom;
const $$createType13 = Stats.createFrom;
const $$createType14 = ScanRoot.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = Group.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = StorageLocations.createFrom;
