// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function CancelScan() {
    return $Call.ByID(2563779232);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(114996913);
}

/**
 * @returns {$CancellablePromise<$models.CatalogView>}
 */
export function GetCatalog() {
    return $Call.ByID(1745937816).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ScanStatus>}
 */
export function GetScanStatus() {
    return $Call.ByID(1054991018).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.StorageSettings>}
 */
export function GetSettings() {
    return $Call.ByID(125815944).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} filename
 * @param {number} limit
 * @returns {$CancellablePromise<$models.ContextPreview>}
 */
export function Preview(filename, limit) {
    return $Call.ByID(4119986269, filename, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string[]} paths
 * @param {boolean} removeCatalogRows
 * @returns {$CancellablePromise<$models.RecycleResponse>}
 */
export function Recycle(paths, removeCatalogRows) {
    return $Call.ByID(2162376516, paths, removeCatalogRows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} confirm
 * @param {string[]} threadIDs
 * @returns {$CancellablePromise<$models.CatalogMutation>}
 */
export function RemoveCatalogRows(confirm, threadIDs) {
    return $Call.ByID(290244671, confirm, threadIDs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function Reveal(filename) {
    return $Call.ByID(3015498062, filename);
}

/**
 * @param {string[]} paths
 * @param {boolean} removeCatalogRows
 * @returns {$CancellablePromise<$models.RecycleReview>}
 */
export function ReviewRecycle(paths, removeCatalogRows) {
    return $Call.ByID(4037232220, paths, removeCatalogRows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {$models.StorageSettingsUpdate} update
 * @returns {$CancellablePromise<$models.StorageSettings>}
 */
export function SaveSettings(update) {
    return $Call.ByID(3183783763, update).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} rootID
 * @param {string} title
 * @returns {$CancellablePromise<$models.TitleAlias>}
 */
export function SaveTitleAlias(rootID, title) {
    return $Call.ByID(956741884, rootID, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {boolean} includeArchived
 * @returns {$CancellablePromise<$models.ScanResult>}
 */
export function Scan(includeArchived) {
    return $Call.ByID(1387378682, includeArchived).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.CatalogView.createFrom;
const $$createType1 = $models.ScanStatus.createFrom;
const $$createType2 = $models.StorageSettings.createFrom;
const $$createType3 = $models.ContextPreview.createFrom;
const $$createType4 = $models.RecycleResponse.createFrom;
const $$createType5 = $models.CatalogMutation.createFrom;
const $$createType6 = $models.RecycleReview.createFrom;
const $$createType7 = $models.TitleAlias.createFrom;
const $$createType8 = $models.ScanResult.createFrom;
